annonces_platform:
    resource: "@AnnoncesPlatformBundle/Resources/config/routing.yml"
    prefix:   /{_local}/annonce
    defaults: 
        _local:      fr
    requirements:
        _local:   fr|en
