<?php

namespace Annonces\PlatformBundle\Repository;

/**
 * AdvertCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
