# src/OC/PlatformBundle/Resources/config/routing.yml
     
annonces_view:
    path:    /reference/{id}
    defaults: 
        _controller: AnnoncesPlatformBundle:Advert:view
    requirements:
        id:   \d+
        
annonces_view_candidature:
    path:    /candidature/{id}
    defaults: 
        _controller: AnnoncesPlatformBundle:Advert:viewCandidature
    requirements:
        id:   \d+
    
annonces_annonce_courtText:
    path:    /{annee}/{courtText}.{_format}
    defaults: 
        _controller: AnnoncesPlatformBundle:Advert:viewCourtText
        _format:     html
    requirements:
        annee:    \d{4}
        _format:  html|xml 
        
        
annonces_ajouter:
    path:    /ajouter
    defaults:
        _controller: AnnoncesPlatformBundle:Advert:ajouter

annonces_modifier:
    path:    /modifier/{id}
    defaults:
        _controller: AnnoncesPlatformBundle:Advert:modifier
    requirements:
        id:    \d+
        
annonces_supprimer:
    path:    supprimer/{id}
    defaults:
        _controller: AnnoncesPlatformBundle:Advert:supprimer
    requirements:
        id:    \d+
        